# Generated by Django 5.2.16 on 2026-07-23 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='codigo')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('last_change_reason', models.TextField(blank=True, verbose_name='ultimo motivo de modificacion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualizacion')),
            ],
            options={
                'verbose_name': 'grouping type',
                'verbose_name_plural': 'grouping types',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('code',), name='real_estate_grouping_type_code_unique')],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='codigo')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('last_change_reason', models.TextField(blank=True, verbose_name='ultimo motivo de modificacion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualizacion')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('code',), name='real_estate_project_code_unique')],
            },
        ),
        migrations.CreateModel(
            name='StructuralGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='codigo')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('last_change_reason', models.TextField(blank=True, verbose_name='ultimo motivo de modificacion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualizacion')),
                ('grouping_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='structural_groups', to='real_estate.groupingtype')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='real_estate.structuralgroup')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='structural_groups', to='real_estate.project')),
            ],
            options={
                'verbose_name': 'structural group',
                'verbose_name_plural': 'structural groups',
                'ordering': ('project__name', 'parent__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PropertyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='codigo')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('last_change_reason', models.TextField(blank=True, verbose_name='ultimo motivo de modificacion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualizacion')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_units', to='real_estate.project')),
                ('structural_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_units', to='real_estate.structuralgroup')),
            ],
            options={
                'verbose_name': 'property unit',
                'verbose_name_plural': 'property units',
                'ordering': ('project__name', 'structural_group__name', 'name'),
            },
        ),
        migrations.AddConstraint(
            model_name='structuralgroup',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('project', 'code'), name='real_estate_structural_group_root_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='structuralgroup',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('parent', 'code'), name='real_estate_structural_group_parent_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='propertyunit',
            constraint=models.UniqueConstraint(condition=models.Q(('structural_group__isnull', True)), fields=('project', 'code'), name='real_estate_property_unit_project_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='propertyunit',
            constraint=models.UniqueConstraint(condition=models.Q(('structural_group__isnull', False)), fields=('structural_group', 'code'), name='real_estate_property_unit_group_code_unique'),
        ),
    ]
