# Generated by Django 5.2.16 on 2026-07-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='propertyunit',
            name='real_estate_property_unit_project_code_unique',
        ),
        migrations.RemoveConstraint(
            model_name='propertyunit',
            name='real_estate_property_unit_group_code_unique',
        ),
        migrations.RemoveConstraint(
            model_name='structuralgroup',
            name='real_estate_structural_group_root_code_unique',
        ),
        migrations.RemoveConstraint(
            model_name='structuralgroup',
            name='real_estate_structural_group_parent_code_unique',
        ),
        migrations.AlterField(
            model_name='propertyunit',
            name='code',
            field=models.CharField(blank=True, max_length=50, verbose_name='codigo'),
        ),
        migrations.AlterField(
            model_name='propertyunit',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='structuralgroup',
            name='code',
            field=models.CharField(blank=True, max_length=50, verbose_name='codigo'),
        ),
        migrations.AlterField(
            model_name='structuralgroup',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='nombre'),
        ),
        migrations.AddConstraint(
            model_name='propertyunit',
            constraint=models.UniqueConstraint(condition=models.Q(('structural_group__isnull', True), models.Q(('code', ''), _negated=True)), fields=('project', 'code'), name='real_estate_property_unit_project_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='propertyunit',
            constraint=models.UniqueConstraint(condition=models.Q(('structural_group__isnull', False), models.Q(('code', ''), _negated=True)), fields=('structural_group', 'code'), name='real_estate_property_unit_group_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='structuralgroup',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True), models.Q(('code', ''), _negated=True)), fields=('project', 'code'), name='real_estate_structural_group_root_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='structuralgroup',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False), models.Q(('code', ''), _negated=True)), fields=('parent', 'code'), name='real_estate_structural_group_parent_code_unique'),
        ),
    ]
