# Generated by Django 5.2.16 on 2026-09-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_remove_propertyunit_real_estate_property_unit_project_code_unique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyunit',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='area'),
        ),
    ]
