# Generated by Django 5.2.16 on 2026-09-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0003_propertyunit_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyunit',
            name='financial_entity',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='entidad financiera'),
        ),
        migrations.AddField(
            model_name='propertyunit',
            name='property_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='valor inmueble'),
        ),
    ]
