# Generated by Django 5.2.16 on 2026-08-11 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('automatic', 'Automático'), ('manual', 'Manual')], max_length=16, verbose_name='tipo')),
                ('status', models.CharField(choices=[('success', 'Exitoso'), ('failed', 'Fallido'), ('pruned', 'Retenido fuera de línea')], default='success', max_length=16, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('file_path', models.TextField(blank=True, verbose_name='ruta física')),
                ('file_name', models.CharField(blank=True, max_length=180, verbose_name='archivo')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='tamaño')),
                ('checksum_sha256', models.CharField(blank=True, max_length=64, verbose_name='checksum SHA-256')),
                ('last_change_at', models.DateTimeField(blank=True, null=True, verbose_name='último cambio detectado')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadatos')),
                ('message', models.TextField(blank=True, verbose_name='mensaje')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='backup_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'backup record',
                'verbose_name_plural': 'backup records',
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['backup_type', 'status', '-created_at'], name='core_backup_type_status_idx'), models.Index(fields=['status', '-created_at'], name='core_backup_status_date_idx')],
            },
        ),
    ]
