# Generated by Django 5.2.16 on 2026-08-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backuprecord',
            name='backup_type',
            field=models.CharField(choices=[('automatic', 'Automático'), ('manual', 'Manual'), ('pre_restore', 'Previo a restauración')], max_length=16, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='backuprecord',
            name='status',
            field=models.CharField(choices=[('success', 'Exitoso'), ('failed', 'Fallido'), ('pruned', 'Retenido fuera de línea'), ('replaced', 'Reemplazado'), ('consumed', 'Consumido')], default='success', max_length=16, verbose_name='estado'),
        ),
    ]
