# Generated by Django 5.2.16 on 2026-08-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_backuprecord_backup_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_check_time', models.TimeField(default='18:00', verbose_name='hora diaria')),
                ('last_auto_check_at', models.DateTimeField(blank=True, null=True, verbose_name='última comprobación automática')),
                ('last_auto_check_result', models.CharField(choices=[('not_run', 'Sin comprobaciones'), ('backup_created', 'Backup creado'), ('no_changes', 'Sin cambios'), ('failed', 'Fallo')], default='not_run', max_length=24, verbose_name='resultado de última comprobación')),
                ('automation_status', models.CharField(choices=[('pending', 'Pendiente de configuración'), ('active', 'Activa')], default='pending', max_length=24, verbose_name='estado de automatización')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'backup settings',
                'verbose_name_plural': 'backup settings',
            },
        ),
        migrations.AlterField(
            model_name='backuprecord',
            name='backup_type',
            field=models.CharField(choices=[('automatic', 'Automático'), ('manual', 'Manual'), ('pre_restore', 'Previo a restauración'), ('uploaded', 'Cargado externo')], max_length=16, verbose_name='tipo'),
        ),
    ]
