# Generated by Django 5.2.16 on 2026-08-18 14:08

import uuid
from django.conf import settings
from django.db import migrations, models


def mark_existing_ordinary_backups_pending(apps, schema_editor):
    BackupRecord = apps.get_model("core", "BackupRecord")
    BackupRecord.objects.filter(
        backup_type__in=["automatic", "manual"],
        status="success",
    ).update(drive_sync_status="pending")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_backupsettings_alter_backuprecord_backup_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='backuprecord',
            name='backup_uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='identificador lógico'),
        ),
        migrations.AddField(
            model_name='backuprecord',
            name='drive_file_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='ID archivo Google Drive'),
        ),
        migrations.AddField(
            model_name='backuprecord',
            name='drive_last_attempt_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='último intento Google Drive'),
        ),
        migrations.AddField(
            model_name='backuprecord',
            name='drive_last_error',
            field=models.TextField(blank=True, verbose_name='último error Google Drive'),
        ),
        migrations.AddField(
            model_name='backuprecord',
            name='drive_sync_status',
            field=models.CharField(choices=[('not_applicable', 'No aplica'), ('pending', 'Pendiente'), ('syncing', 'Sincronizando'), ('synced', 'Sincronizado'), ('failed', 'Error')], db_index=True, default='not_applicable', max_length=20, verbose_name='estado Google Drive'),
        ),
        migrations.AddField(
            model_name='backuprecord',
            name='drive_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha sincronización Google Drive'),
        ),
        migrations.AddIndex(
            model_name='backuprecord',
            index=models.Index(fields=['backup_type', 'drive_sync_status'], name='core_backup_drive_status_idx'),
        ),
        migrations.RunPython(mark_existing_ordinary_backups_pending, migrations.RunPython.noop),
    ]
