# Generated by Django 5.2.16 on 2026-09-15 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_known_human_events(apps, schema_editor):
    AuditEvent = apps.get_model("core", "AuditEvent")
    ImportAppliedRecord = apps.get_model("fiduciary", "ImportAppliedRecord")
    LogEntry = apps.get_model("admin", "LogEntry")

    for record in ImportAppliedRecord.objects.filter(source_column="__AUDIT__").select_related("batch", "imported_file"):
        lines = [line.strip() for line in (record.summary or "").splitlines() if line.strip()]
        parsed = _parse_lines(lines)
        batch = record.batch
        user_id = getattr(batch, "imported_by_id", None) or getattr(batch, "initiated_by_id", None)
        AuditEvent.objects.create(
            user_id=user_id,
            action=parsed.pop("Accion", record.get_action_display() if hasattr(record, "get_action_display") else record.action),
            entity=parsed.pop("Entidad", record.entity_kind),
            entity_id=str(record.entity_id or ""),
            entity_repr=str(record)[:200],
            description=parsed.pop("Descripcion", ""),
            context={
                "Archivo": getattr(record.imported_file, "original_name", "") if record.imported_file_id else "",
                "Lote": record.batch_id,
            },
            summary=parsed,
        )

    for log in LogEntry.objects.exclude(change_message="").order_by("action_time", "pk"):
        message = log.change_message or ""
        if "Accion:" not in message and not _looks_like_human_code(message):
            continue
        parsed = _parse_lines([part.strip() for part in message.split("|") if part.strip()])
        action = parsed.pop("Accion", _action_from_log(log, message))
        entity = parsed.pop("Entidad", log.content_type.name if log.content_type_id else "Registro")
        AuditEvent.objects.create(
            user_id=log.user_id,
            action=action,
            entity=entity,
            entity_id=str(log.object_id or ""),
            entity_repr=log.object_repr or "",
            description=parsed.pop("Descripcion", message[:500]),
            reason=parsed.pop("Motivo", ""),
            context=parsed,
        )


def _parse_lines(lines):
    parsed = {}
    for line in lines:
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        parsed[key.strip()] = value.strip()
    return parsed


def _looks_like_human_code(message):
    return any(
        code in message
        for code in (
            "ELIMINAR_",
            "MODIFICAR_",
            "CREAR_",
            "INACTIVAR_USUARIO",
        )
    )


def _action_from_log(log, message):
    if "ELIMINAR_" in message:
        return "Eliminado"
    if "CREAR_" in message:
        return "Creado"
    if log.action_flag == 1:
        return "Creado"
    if log.action_flag == 3:
        return "Eliminado"
    return "Modificado"


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('core', '0004_backuprecord_backup_uid_backuprecord_drive_file_id_and_more'),
        ('fiduciary', '0017_remove_importedfile_fiduciary_imported_file_historical_sha_unique_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80, verbose_name='accion')),
                ('entity', models.CharField(max_length=120, verbose_name='entidad')),
                ('entity_id', models.CharField(blank=True, max_length=80, verbose_name='id de entidad')),
                ('entity_repr', models.CharField(blank=True, max_length=200, verbose_name='representacion de entidad')),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
                ('reason', models.TextField(blank=True, verbose_name='motivo')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='contexto')),
                ('before', models.JSONField(blank=True, default=dict, verbose_name='antes')),
                ('after', models.JSONField(blank=True, default=dict, verbose_name='despues')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='resumen')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha de creacion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit event',
                'verbose_name_plural': 'audit events',
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['action', '-created_at'], name='core_audit_action_date_idx'), models.Index(fields=['entity', '-created_at'], name='core_audit_entity_date_idx')],
            },
        ),
        migrations.RunPython(migrate_known_human_events, migrations.RunPython.noop),
    ]
