# Generated by Django 5.2.16 on 2026-07-24 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('real_estate', '0002_remove_propertyunit_real_estate_property_unit_project_code_unique_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_change_reason', models.TextField(blank=True, verbose_name='ultimo motivo de modificacion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualizacion')),
                ('document_type', models.CharField(choices=[('cc', 'Cedula de ciudadania'), ('ce', 'Cedula de extranjeria'), ('passport', 'Pasaporte'), ('nit', 'NIT')], max_length=16, verbose_name='tipo de documento')),
                ('document_number', models.CharField(max_length=50, verbose_name='numero de documento')),
                ('first_names', models.CharField(blank=True, max_length=150, verbose_name='nombres')),
                ('last_names_or_company', models.CharField(max_length=180, verbose_name='apellidos o razon social')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='telefono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electronico')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='direccion')),
                ('information_status', models.CharField(choices=[('complete', 'Completo'), ('incomplete', 'Incompleto')], default='complete', max_length=16, verbose_name='estado de informacion')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'ordering': ('last_names_or_company', 'first_names', 'document_number'),
                'constraints': [models.UniqueConstraint(fields=('document_type', 'document_number'), name='fiduciary_client_document_unique'), models.CheckConstraint(condition=models.Q(('information_status__in', ['complete', 'incomplete'])), name='fiduciary_client_information_status_valid')],
            },
        ),
        migrations.CreateModel(
            name='FiduciaryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_change_reason', models.TextField(blank=True, verbose_name='ultimo motivo de modificacion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualizacion')),
                ('start_date', models.DateField(verbose_name='fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='fecha de finalizacion')),
                ('is_active', models.BooleanField(default=True, verbose_name='vigente')),
                ('assignment_number', models.CharField(max_length=80, verbose_name='numero de encargo fiduciario')),
                ('observations', models.TextField(blank=True, verbose_name='observaciones')),
                ('property_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiduciary_assignments', to='real_estate.propertyunit')),
            ],
            options={
                'ordering': ('property_unit__project__name', 'property_unit__name', '-start_date'),
            },
        ),
        migrations.CreateModel(
            name='FiduciaryAssignmentHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_change_reason', models.TextField(blank=True, verbose_name='ultimo motivo de modificacion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualizacion')),
                ('start_date', models.DateField(verbose_name='fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='fecha de finalizacion')),
                ('is_active', models.BooleanField(default=True, verbose_name='vigente')),
                ('is_primary', models.BooleanField(default=False, verbose_name='titular principal')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holders', to='fiduciary.fiduciaryassignment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiduciary_assignment_holders', to='fiduciary.client')),
            ],
            options={
                'ordering': ('assignment__assignment_number', '-is_active', '-is_primary', 'client__last_names_or_company'),
            },
        ),
        migrations.CreateModel(
            name='UnitOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_change_reason', models.TextField(blank=True, verbose_name='ultimo motivo de modificacion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualizacion')),
                ('start_date', models.DateField(verbose_name='fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='fecha de finalizacion')),
                ('is_active', models.BooleanField(default=True, verbose_name='vigente')),
                ('is_primary', models.BooleanField(default=False, verbose_name='titular principal')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_ownerships', to='fiduciary.client')),
                ('property_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ownerships', to='real_estate.propertyunit')),
            ],
            options={
                'ordering': ('property_unit__project__name', 'property_unit__name', '-is_active', '-is_primary'),
            },
        ),
        migrations.AddConstraint(
            model_name='fiduciaryassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('property_unit',), name='fiduciary_assignment_one_active_per_unit'),
        ),
        migrations.AddConstraint(
            model_name='fiduciaryassignmentholder',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('assignment',), name='fiduciary_assignment_one_active_primary_holder'),
        ),
        migrations.AddConstraint(
            model_name='fiduciaryassignmentholder',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('assignment', 'client'), name='fiduciary_assignment_active_client_unique'),
        ),
        migrations.AddConstraint(
            model_name='unitownership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('property_unit',), name='fiduciary_unit_one_active_primary_owner'),
        ),
        migrations.AddConstraint(
            model_name='unitownership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('client', 'property_unit'), name='fiduciary_unit_active_client_unique'),
        ),
    ]
