# Generated by Django 5.2.16 on 2026-07-27 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0001_initial'),
        ('real_estate', '0002_remove_propertyunit_real_estate_property_unit_project_code_unique_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedStructureElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_value', models.CharField(max_length=255, verbose_name='valor detectado')),
                ('normalized_value', models.CharField(max_length=255, verbose_name='valor normalizado')),
                ('inferred_kind', models.CharField(choices=[('project', 'Proyecto'), ('grouping_type', 'Tipo de agrupacion'), ('structural_group', 'Agrupacion'), ('property_unit', 'Unidad'), ('unknown', 'Desconocido')], default='unknown', max_length=32, verbose_name='tipo inferido')),
                ('structural_context', models.JSONField(blank=True, default=dict, verbose_name='contexto estructural sanitizado')),
                ('occurrence_count', models.PositiveIntegerField(default=1, verbose_name='ocurrencias')),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='confianza')),
                ('status', models.CharField(choices=[('detected', 'Detectado'), ('auto_matched', 'Asociado automaticamente'), ('needs_review', 'Requiere revision'), ('resolved', 'Resuelto'), ('ignored', 'Ignorado')], default='detected', max_length=24, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualizacion')),
            ],
            options={
                'ordering': ('batch', 'inferred_kind', 'normalized_value'),
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('historical', 'Historico'), ('reports', 'Reportes')], max_length=16, verbose_name='tipo de importacion')),
                ('load_mode', models.CharField(choices=[('single_file', 'Archivo individual'), ('folder', 'Carpeta')], default='single_file', max_length=16, verbose_name='modo de carga')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('analyzing', 'Analizando'), ('awaiting_resolution', 'Pendiente de resolucion'), ('ready', 'Listo'), ('processing', 'Procesando'), ('completed', 'Completado'), ('completed_with_issues', 'Completado con incidencias'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='pending', max_length=32, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('processing_started_at', models.DateTimeField(blank=True, null=True, verbose_name='inicio de procesamiento')),
                ('processing_finished_at', models.DateTimeField(blank=True, null=True, verbose_name='fin de procesamiento')),
                ('total_files', models.PositiveIntegerField(default=0, verbose_name='archivos totales')),
                ('processed_files', models.PositiveIntegerField(default=0, verbose_name='archivos procesados')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='filas totales')),
                ('processed_rows', models.PositiveIntegerField(default=0, verbose_name='filas procesadas')),
                ('issue_count', models.PositiveIntegerField(default=0, verbose_name='incidencias')),
                ('summary', models.TextField(blank=True, verbose_name='resumen sanitizado')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ImportedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255, verbose_name='nombre original')),
                ('extension', models.CharField(max_length=16, verbose_name='extension')),
                ('size_bytes', models.PositiveBigIntegerField(verbose_name='tamano en bytes')),
                ('sha256', models.CharField(max_length=64, verbose_name='sha-256')),
                ('file_type', models.CharField(choices=[('historical', 'Historico'), ('report', 'Reporte'), ('unknown', 'Desconocido')], default='unknown', max_length=16, verbose_name='tipo de archivo')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('analyzing', 'Analizando'), ('ready', 'Listo'), ('processing', 'Procesando'), ('completed', 'Completado'), ('completed_with_issues', 'Completado con incidencias'), ('failed', 'Fallido'), ('duplicate', 'Duplicado'), ('cancelled', 'Cancelado')], default='pending', max_length=32, verbose_name='estado')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('processing_started_at', models.DateTimeField(blank=True, null=True, verbose_name='inicio de procesamiento')),
                ('processing_finished_at', models.DateTimeField(blank=True, null=True, verbose_name='fin de procesamiento')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='filas totales')),
                ('processed_rows', models.PositiveIntegerField(default=0, verbose_name='filas procesadas')),
                ('skipped_rows', models.PositiveIntegerField(default=0, verbose_name='filas omitidas')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='errores')),
                ('warning_count', models.PositiveIntegerField(default=0, verbose_name='advertencias')),
                ('result_message', models.TextField(blank=True, verbose_name='mensaje sanitizado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
            ],
            options={
                'ordering': ('batch', 'order', 'original_name'),
            },
        ),
        migrations.CreateModel(
            name='ImportedSheetResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=150, verbose_name='nombre de hoja')),
                ('sheet_index', models.PositiveIntegerField(verbose_name='indice')),
                ('visibility', models.CharField(choices=[('visible', 'Visible'), ('hidden', 'Oculta'), ('very_hidden', 'Muy oculta')], default='visible', max_length=16, verbose_name='visibilidad')),
                ('classification', models.CharField(choices=[('processable', 'Procesable'), ('auxiliary', 'Auxiliar'), ('summary', 'Resumen'), ('empty', 'Vacia'), ('unknown', 'Desconocida')], default='unknown', max_length=16, verbose_name='clasificacion')),
                ('header_row', models.PositiveIntegerField(blank=True, null=True, verbose_name='fila de encabezado')),
                ('detected_dimension', models.CharField(blank=True, max_length=50, verbose_name='dimension detectada')),
                ('analyzed_rows', models.PositiveIntegerField(default=0, verbose_name='filas analizadas')),
                ('processed_rows', models.PositiveIntegerField(default=0, verbose_name='filas procesadas')),
                ('skipped_rows', models.PositiveIntegerField(default=0, verbose_name='filas omitidas')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='errores')),
                ('warning_count', models.PositiveIntegerField(default=0, verbose_name='advertencias')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('analyzed', 'Analizada'), ('processed', 'Procesada'), ('skipped', 'Omitida'), ('failed', 'Fallida')], default='pending', max_length=16, verbose_name='estado')),
                ('summary', models.TextField(blank=True, verbose_name='resumen sanitizado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualizacion')),
            ],
            options={
                'ordering': ('imported_file', 'sheet_index'),
            },
        ),
        migrations.CreateModel(
            name='ImportNovelty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novelty_type', models.CharField(choices=[('assignment_change', 'Cambio de encargo'), ('transfer', 'Cesion'), ('relocation', 'Traslado'), ('withdrawal', 'Retiro'), ('ambiguous_holder', 'Titular ambiguo'), ('incompatible_structure', 'Estructura incompatible')], max_length=32, verbose_name='tipo de novedad')),
                ('status', models.CharField(choices=[('detected', 'Detectada'), ('pending_review', 'Pendiente de revision'), ('resolved', 'Resuelta'), ('dismissed', 'Descartada')], default='detected', max_length=24, verbose_name='estado')),
                ('description', models.TextField(blank=True, verbose_name='descripcion sanitizada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualizacion')),
            ],
            options={
                'ordering': ('batch', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='ImportResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('associate_existing', 'Asociar existente'), ('create_new', 'Crear nuevo'), ('ignore', 'Ignorar'), ('unresolved', 'Sin resolver')], default='unresolved', max_length=24, verbose_name='accion')),
                ('target_kind', models.CharField(choices=[('project', 'Proyecto'), ('grouping_type', 'Tipo de agrupacion'), ('structural_group', 'Agrupacion'), ('property_unit', 'Unidad'), ('unknown', 'Desconocido')], default='unknown', max_length=32, verbose_name='tipo destino')),
                ('create_code', models.CharField(blank=True, max_length=80, verbose_name='codigo a crear')),
                ('create_name', models.CharField(blank=True, max_length=180, verbose_name='nombre a crear')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de resolucion')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('applied', 'Aplicada'), ('rejected', 'Rechazada')], default='draft', max_length=16, verbose_name='estado')),
            ],
            options={
                'ordering': ('detected_element',),
            },
        ),
        migrations.CreateModel(
            name='ImportRowIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='fila')),
                ('column_letter', models.CharField(blank=True, max_length=10, verbose_name='columna')),
                ('severity', models.CharField(choices=[('info', 'Informacion'), ('warning', 'Advertencia'), ('error', 'Error'), ('blocking', 'Bloqueante')], max_length=16, verbose_name='severidad')),
                ('code', models.CharField(max_length=80, verbose_name='codigo')),
                ('message', models.TextField(verbose_name='mensaje sanitizado')),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('resolved', 'Resuelta'), ('ignored', 'Ignorada')], default='open', max_length=16, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
            ],
            options={
                'ordering': ('imported_file', 'sheet_result', 'row_number', 'column_letter', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_change_reason', models.TextField(blank=True, verbose_name='ultimo motivo de modificacion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualizacion')),
                ('exact_date', models.DateField(blank=True, null=True, verbose_name='fecha exacta')),
                ('period_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ano del periodo')),
                ('period_month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='mes del periodo')),
                ('date_precision', models.CharField(choices=[('exact', 'Fecha exacta'), ('month', 'Periodo mensual')], max_length=8, verbose_name='precision de fecha')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='valor')),
                ('concept', models.CharField(blank=True, max_length=180, null=True, verbose_name='concepto')),
                ('movement_type', models.CharField(choices=[('historical_payment', 'Pago historico'), ('addition', 'Adicion'), ('withdrawal', 'Retiro')], max_length=24, verbose_name='tipo de movimiento')),
                ('source_sheet', models.CharField(max_length=150, verbose_name='hoja origen')),
                ('source_row', models.PositiveIntegerField(verbose_name='fila origen')),
                ('source_column', models.CharField(blank=True, max_length=10, null=True, verbose_name='columna origen')),
                ('source_header', models.CharField(blank=True, max_length=180, null=True, verbose_name='encabezado origen')),
                ('source_had_formula', models.BooleanField(default=False, verbose_name='origen con formula')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de importacion')),
            ],
            options={
                'ordering': ('assignment', '-exact_date', '-period_year', '-period_month', '-created_at'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='client',
            name='fiduciary_client_document_unique',
        ),
        migrations.AddField(
            model_name='client',
            name='incomplete_reason',
            field=models.TextField(blank=True, verbose_name='motivo de informacion incompleta'),
        ),
        migrations.AddField(
            model_name='client',
            name='source_origin',
            field=models.CharField(choices=[('manual', 'Manual'), ('historical_import', 'Importacion historica'), ('report_import', 'Importacion de reporte')], default='manual', max_length=24, verbose_name='origen del registro'),
        ),
        migrations.AlterField(
            model_name='client',
            name='document_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='numero de documento'),
        ),
        migrations.AlterField(
            model_name='client',
            name='document_type',
            field=models.CharField(choices=[('cc', 'Cedula de ciudadania'), ('ce', 'Cedula de extranjeria'), ('passport', 'Pasaporte'), ('nit', 'NIT'), ('unknown', 'Desconocido')], default='unknown', max_length=16, verbose_name='tipo de documento'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('document_number__isnull', False), models.Q(('document_number', ''), _negated=True)), fields=('document_type', 'document_number'), name='fiduciary_client_document_unique'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.CheckConstraint(condition=models.Q(('source_origin__in', ['manual', 'historical_import', 'report_import'])), name='fiduciary_client_source_origin_valid'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='initiated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detectedstructureelement',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detected_elements', to='fiduciary.importbatch'),
        ),
        migrations.AddField(
            model_name='importedfile',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='fiduciary.importbatch'),
        ),
        migrations.AddField(
            model_name='detectedstructureelement',
            name='imported_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detected_elements', to='fiduciary.importedfile'),
        ),
        migrations.AddField(
            model_name='importedsheetresult',
            name='imported_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sheet_results', to='fiduciary.importedfile'),
        ),
        migrations.AddField(
            model_name='importnovelty',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_novelties', to='fiduciary.fiduciaryassignment'),
        ),
        migrations.AddField(
            model_name='importnovelty',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novelties', to='fiduciary.importbatch'),
        ),
        migrations.AddField(
            model_name='importnovelty',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_novelties', to='fiduciary.client'),
        ),
        migrations.AddField(
            model_name='importnovelty',
            name='imported_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='novelties', to='fiduciary.importedfile'),
        ),
        migrations.AddField(
            model_name='importnovelty',
            name='property_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_novelties', to='real_estate.propertyunit'),
        ),
        migrations.AddField(
            model_name='importnovelty',
            name='sheet_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='novelties', to='fiduciary.importedsheetresult'),
        ),
        migrations.AddField(
            model_name='importresolution',
            name='detected_element',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='resolution', to='fiduciary.detectedstructureelement'),
        ),
        migrations.AddField(
            model_name='importresolution',
            name='parent_grouping_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_parent_resolutions', to='real_estate.groupingtype'),
        ),
        migrations.AddField(
            model_name='importresolution',
            name='parent_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_parent_resolutions', to='real_estate.project'),
        ),
        migrations.AddField(
            model_name='importresolution',
            name='parent_structural_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_parent_resolutions', to='real_estate.structuralgroup'),
        ),
        migrations.AddField(
            model_name='importresolution',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_resolutions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importresolution',
            name='target_grouping_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_target_resolutions', to='real_estate.groupingtype'),
        ),
        migrations.AddField(
            model_name='importresolution',
            name='target_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_target_resolutions', to='real_estate.project'),
        ),
        migrations.AddField(
            model_name='importresolution',
            name='target_property_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_target_resolutions', to='real_estate.propertyunit'),
        ),
        migrations.AddField(
            model_name='importresolution',
            name='target_structural_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_target_resolutions', to='real_estate.structuralgroup'),
        ),
        migrations.AddField(
            model_name='importrowissue',
            name='imported_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='row_issues', to='fiduciary.importedfile'),
        ),
        migrations.AddField(
            model_name='importrowissue',
            name='sheet_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='row_issues', to='fiduciary.importedsheetresult'),
        ),
        migrations.AddField(
            model_name='payment',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='fiduciary.fiduciaryassignment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='source_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='fiduciary.importedfile'),
        ),
        migrations.AddField(
            model_name='importnovelty',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_novelties', to='fiduciary.payment'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=models.Q(('import_type__in', ['historical', 'reports'])), name='fiduciary_import_batch_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=models.Q(('load_mode__in', ['single_file', 'folder'])), name='fiduciary_import_batch_load_mode_valid'),
        ),
        migrations.AddIndex(
            model_name='importedfile',
            index=models.Index(fields=['sha256'], name='fiduciary_file_sha_idx'),
        ),
        migrations.AddIndex(
            model_name='importedfile',
            index=models.Index(fields=['status'], name='fiduciary_file_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='importedfile',
            constraint=models.UniqueConstraint(fields=('batch', 'sha256'), name='fiduciary_imported_file_batch_sha_unique'),
        ),
        migrations.AddConstraint(
            model_name='importedfile',
            constraint=models.CheckConstraint(condition=models.Q(('file_type__in', ['historical', 'report', 'unknown'])), name='fiduciary_imported_file_type_valid'),
        ),
        migrations.AddIndex(
            model_name='detectedstructureelement',
            index=models.Index(fields=['batch', 'normalized_value'], name='fiduciary_detected_norm_idx'),
        ),
        migrations.AddIndex(
            model_name='detectedstructureelement',
            index=models.Index(fields=['status'], name='fiduciary_detected_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='importedsheetresult',
            constraint=models.UniqueConstraint(fields=('imported_file', 'sheet_name'), name='fiduciary_sheet_file_name_unique'),
        ),
        migrations.AddIndex(
            model_name='importrowissue',
            index=models.Index(fields=['severity', 'status'], name='fiduciary_issue_sev_status_idx'),
        ),
        migrations.AddIndex(
            model_name='importrowissue',
            index=models.Index(fields=['code'], name='fiduciary_issue_code_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['assignment', 'exact_date', 'amount'], name='fiduciary_payment_exact_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['assignment', 'period_year', 'period_month', 'amount'], name='fiduciary_payment_month_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['source_file', 'source_sheet', 'source_row', 'source_column'], name='fiduciary_payment_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='fiduciary_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('date_precision__in', ['exact', 'month'])), name='fiduciary_payment_date_precision_valid'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('movement_type__in', ['historical_payment', 'addition', 'withdrawal'])), name='fiduciary_payment_movement_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('date_precision', 'exact'), ('exact_date__isnull', False), ('period_month__isnull', True), ('period_year__isnull', True)), models.Q(('date_precision', 'month'), ('exact_date__isnull', True), ('period_month__isnull', False), ('period_year__isnull', False)), _connector='OR'), name='fiduciary_payment_one_date_mode'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('period_month__isnull', True), models.Q(('period_month__gte', 1), ('period_month__lte', 12)), _connector='OR'), name='fiduciary_payment_period_month_range'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('date_precision', 'exact')), fields=('assignment', 'exact_date', 'amount'), name='fiduciary_payment_exact_unique'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('date_precision', 'month')), fields=('assignment', 'period_year', 'period_month', 'amount'), name='fiduciary_payment_month_unique'),
        ),
        migrations.AddIndex(
            model_name='importnovelty',
            index=models.Index(fields=['novelty_type', 'status'], name='fiduciary_novelty_status_idx'),
        ),
    ]
