# Generated by Django 5.2.16 on 2026-07-28 13:42

from django.db import migrations, models


ADVANCED_BATCH_STATUS_RANK = {
    "completed": 8,
    "completed_with_issues": 7,
    "ready": 6,
    "awaiting_resolution": 5,
    "processing": 4,
    "analyzing": 3,
    "pending": 2,
    "failed": 1,
    "cancelled": 0,
}


def cleanup_duplicate_historical_files(apps, schema_editor):
    ImportedFile = apps.get_model("fiduciary", "ImportedFile")
    ImportedSheetResult = apps.get_model("fiduciary", "ImportedSheetResult")
    ImportRowIssue = apps.get_model("fiduciary", "ImportRowIssue")
    DetectedStructureElement = apps.get_model("fiduciary", "DetectedStructureElement")
    ImportResolution = apps.get_model("fiduciary", "ImportResolution")
    ImportBatch = apps.get_model("fiduciary", "ImportBatch")
    Payment = apps.get_model("fiduciary", "Payment")
    ImportNovelty = apps.get_model("fiduciary", "ImportNovelty")

    duplicate_hashes = (
        ImportedFile.objects.filter(file_type="historical")
        .values_list("sha256", flat=True)
        .annotate(total=models.Count("id"))
        .filter(total__gt=1)
    )

    for sha256 in duplicate_hashes:
        files = list(ImportedFile.objects.filter(file_type="historical", sha256=sha256).select_related("batch"))

        def sort_key(imported_file):
            has_business_refs = (
                Payment.objects.filter(source_file_id=imported_file.pk).exists()
                or ImportNovelty.objects.filter(imported_file_id=imported_file.pk).exists()
            )
            batch_rank = ADVANCED_BATCH_STATUS_RANK.get(imported_file.batch.status, -1)
            created_at = imported_file.created_at
            return (1 if has_business_refs else 0, batch_rank, -created_at.timestamp(), -imported_file.pk)

        canonical = sorted(files, key=sort_key, reverse=True)[0]
        for duplicate in files:
            if duplicate.pk == canonical.pk:
                continue
            has_business_refs = (
                Payment.objects.filter(source_file_id=duplicate.pk).exists()
                or ImportNovelty.objects.filter(imported_file_id=duplicate.pk).exists()
            )
            if has_business_refs:
                raise RuntimeError(
                    "No es seguro consolidar automaticamente archivos historicos duplicados con entidades de negocio."
                )

            duplicate_elements = DetectedStructureElement.objects.filter(imported_file_id=duplicate.pk)
            ImportResolution.objects.filter(detected_element_id__in=duplicate_elements.values("id")).delete()
            duplicate_elements.delete()
            ImportRowIssue.objects.filter(imported_file_id=duplicate.pk).delete()
            ImportedSheetResult.objects.filter(imported_file_id=duplicate.pk).delete()
            duplicate_batch_id = duplicate.batch_id
            duplicate.delete()

            duplicate_batch = ImportBatch.objects.filter(pk=duplicate_batch_id, import_type="historical").first()
            if duplicate_batch and not (
                ImportedFile.objects.filter(batch_id=duplicate_batch_id).exists()
                or DetectedStructureElement.objects.filter(batch_id=duplicate_batch_id).exists()
                or ImportNovelty.objects.filter(batch_id=duplicate_batch_id).exists()
            ):
                duplicate_batch.delete()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('fiduciary', '0002_detectedstructureelement_importbatch_importedfile_and_more'),
    ]

    operations = [
        migrations.RunPython(cleanup_duplicate_historical_files, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='importedfile',
            constraint=models.UniqueConstraint(condition=models.Q(('file_type', 'historical')), fields=('sha256',), name='fiduciary_imported_file_historical_sha_unique'),
        ),
    ]
