# Generated by Django 5.2.16 on 2026-07-28 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0003_importedfile_fiduciary_imported_file_historical_sha_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedHistoricalNovelty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(verbose_name='fila origen')),
                ('project_name', models.CharField(max_length=180, verbose_name='proyecto detectado')),
                ('grouping_type_name', models.CharField(blank=True, max_length=120, verbose_name='tipo de agrupacion detectado')),
                ('grouping_code', models.CharField(blank=True, max_length=80, verbose_name='codigo de agrupacion')),
                ('grouping_name', models.CharField(blank=True, max_length=180, verbose_name='agrupacion detectada')),
                ('unit_code', models.CharField(blank=True, max_length=80, verbose_name='codigo de unidad')),
                ('unit_name', models.CharField(blank=True, max_length=180, verbose_name='unidad detectada')),
                ('assignment_number', models.CharField(blank=True, max_length=80, verbose_name='encargo fiduciario detectado')),
                ('assignment_status', models.CharField(blank=True, max_length=80, verbose_name='estado del encargo detectado')),
                ('original_cells', models.JSONField(blank=True, default=list, verbose_name='celdas originales')),
                ('sanitized_summary', models.TextField(blank=True, verbose_name='resumen sanitizado')),
                ('status', models.CharField(choices=[('detected', 'Detectada'), ('ready', 'Preparada'), ('ignored', 'Ignorada')], default='detected', max_length=16, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualizacion')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historical_novelties', to='fiduciary.importbatch')),
                ('imported_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historical_novelties', to='fiduciary.importedfile')),
                ('sheet_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historical_novelties', to='fiduciary.importedsheetresult')),
            ],
            options={
                'ordering': ('imported_file', 'sheet_result', 'row_number'),
                'indexes': [models.Index(fields=['batch', 'status'], name='fid_histnov_batch_status_idx'), models.Index(fields=['imported_file', 'row_number'], name='fiduciary_histnov_file_row_idx'), models.Index(fields=['unit_code'], name='fiduciary_histnov_unit_idx'), models.Index(fields=['assignment_number'], name='fid_histnov_assignment_idx')],
                'constraints': [models.UniqueConstraint(fields=('imported_file', 'sheet_result', 'row_number'), name='fiduciary_histnov_file_sheet_row_unique'), models.CheckConstraint(condition=models.Q(('status__in', ['detected', 'ready', 'ignored'])), name='fiduciary_histnov_status_valid')],
            },
        ),
    ]
