# Generated by Django 5.2.16 on 2026-07-28 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0004_importedhistoricalnovelty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='imported_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de importacion definitiva'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='imported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_import_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importedfile',
            name='stored_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='ruta interna del archivo'),
        ),
        migrations.AlterField(
            model_name='fiduciaryassignment',
            name='assignment_number',
            field=models.CharField(max_length=80, unique=True, verbose_name='numero de encargo fiduciario'),
        ),
        migrations.CreateModel(
            name='ImportAppliedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_kind', models.CharField(choices=[('project', 'Proyecto'), ('grouping_type', 'Tipo de agrupacion'), ('structural_group', 'Agrupacion'), ('property_unit', 'Unidad'), ('client', 'Cliente'), ('unit_ownership', 'Titularidad'), ('fiduciary_assignment', 'Encargo fiduciario'), ('assignment_holder', 'Titular de encargo'), ('payment', 'Pago'), ('historical_novelty', 'Novedad historica')], max_length=32, verbose_name='tipo de entidad')),
                ('entity_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='id de entidad')),
                ('action', models.CharField(choices=[('created', 'Creado'), ('reused', 'Reutilizado'), ('skipped', 'Omitido'), ('preserved', 'Conservado')], max_length=16, verbose_name='accion')),
                ('source_row', models.PositiveIntegerField(blank=True, null=True, verbose_name='fila origen')),
                ('source_column', models.CharField(blank=True, max_length=10, verbose_name='columna origen')),
                ('summary', models.TextField(blank=True, verbose_name='resumen sanitizado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applied_records', to='fiduciary.importbatch')),
                ('imported_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applied_records', to='fiduciary.importedfile')),
                ('sheet_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applied_records', to='fiduciary.importedsheetresult')),
            ],
            options={
                'ordering': ('batch', 'created_at'),
                'indexes': [models.Index(fields=['batch', 'entity_kind'], name='fid_applied_batch_kind_idx'), models.Index(fields=['imported_file', 'source_row'], name='fid_applied_file_row_idx')],
            },
        ),
    ]
