# Generated by Django 5.2.16 on 2026-07-29 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0005_importbatch_imported_at_importbatch_imported_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=150, verbose_name='hoja')),
                ('row_number', models.PositiveIntegerField(verbose_name='fila origen')),
                ('original_assignment_number', models.CharField(blank=True, max_length=120, verbose_name='encargo original')),
                ('normalized_assignment_number', models.CharField(blank=True, max_length=120, verbose_name='encargo normalizado')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='fecha de pago')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='valor')),
                ('movement_type', models.CharField(choices=[('historical_payment', 'Pago historico'), ('addition', 'Adicion'), ('withdrawal', 'Retiro')], default='addition', max_length=24, verbose_name='tipo de movimiento')),
                ('payer_name', models.CharField(blank=True, max_length=180, verbose_name='pagador')),
                ('payer_document', models.CharField(blank=True, max_length=80, verbose_name='identificacion del pagador')),
                ('concept', models.CharField(blank=True, max_length=180, verbose_name='concepto')),
                ('original_data', models.JSONField(blank=True, default=dict, verbose_name='datos originales sanitizados')),
                ('status', models.CharField(choices=[('valid', 'Valida'), ('duplicate', 'Duplicada'), ('assignment_not_found', 'Encargo no encontrado'), ('invalid_assignment', 'Encargo invalido'), ('invalid_date', 'Fecha invalida'), ('invalid_amount', 'Valor invalido'), ('needs_review', 'Requiere revision'), ('imported', 'Importada'), ('failed', 'Fallida')], max_length=32, verbose_name='estado')),
                ('message', models.TextField(blank=True, verbose_name='mensaje')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de resolucion')),
                ('resolution_note', models.TextField(blank=True, verbose_name='nota de resolucion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualizacion')),
            ],
            options={
                'ordering': ('imported_file', 'sheet_name', 'row_number'),
            },
        ),
        migrations.AlterField(
            model_name='importappliedrecord',
            name='entity_kind',
            field=models.CharField(choices=[('project', 'Proyecto'), ('grouping_type', 'Tipo de agrupacion'), ('structural_group', 'Agrupacion'), ('property_unit', 'Unidad'), ('client', 'Cliente'), ('unit_ownership', 'Titularidad'), ('fiduciary_assignment', 'Encargo fiduciario'), ('assignment_holder', 'Titular de encargo'), ('payment', 'Pago'), ('historical_novelty', 'Novedad historica'), ('daily_report_row', 'Fila de reporte diario')], max_length=32, verbose_name='tipo de entidad'),
        ),
        migrations.AddConstraint(
            model_name='importedfile',
            constraint=models.UniqueConstraint(condition=models.Q(('file_type', 'report')), fields=('sha256',), name='fiduciary_imported_file_report_sha_unique'),
        ),
        migrations.AddField(
            model_name='dailyreportrow',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_report_rows', to='fiduciary.fiduciaryassignment'),
        ),
        migrations.AddField(
            model_name='dailyreportrow',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_report_rows', to='fiduciary.importbatch'),
        ),
        migrations.AddField(
            model_name='dailyreportrow',
            name='imported_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_report_rows', to='fiduciary.importedfile'),
        ),
        migrations.AddField(
            model_name='dailyreportrow',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_report_rows', to='fiduciary.payment'),
        ),
        migrations.AddField(
            model_name='dailyreportrow',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_daily_report_rows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyreportrow',
            name='sheet_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_report_rows', to='fiduciary.importedsheetresult'),
        ),
        migrations.AddIndex(
            model_name='dailyreportrow',
            index=models.Index(fields=['batch', 'status'], name='fid_daily_row_batch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreportrow',
            index=models.Index(fields=['normalized_assignment_number'], name='fid_daily_row_assignment_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreportrow',
            index=models.Index(fields=['assignment', 'payment_date', 'amount'], name='fid_daily_row_payment_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyreportrow',
            constraint=models.UniqueConstraint(fields=('imported_file', 'sheet_name', 'row_number'), name='fid_daily_row_file_sheet_row_unique'),
        ),
        migrations.AddConstraint(
            model_name='dailyreportrow',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['valid', 'duplicate', 'assignment_not_found', 'invalid_assignment', 'invalid_date', 'invalid_amount', 'needs_review', 'imported', 'failed'])), name='fid_daily_row_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='dailyreportrow',
            constraint=models.CheckConstraint(condition=models.Q(('movement_type__in', ['historical_payment', 'addition', 'withdrawal'])), name='fid_daily_row_movement_type_valid'),
        ),
    ]
