# Generated by Django 5.2.16 on 2026-07-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0006_dailyreportrow_alter_importappliedrecord_entity_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='last_names_or_company',
            field=models.CharField(blank=True, max_length=180, verbose_name='apellidos o razon social'),
        ),
    ]
