# Generated by Django 5.2.16 on 2026-07-29 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0007_alter_client_last_names_or_company'),
        ('real_estate', '0002_remove_propertyunit_real_estate_property_unit_project_code_unique_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedHistoricalObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(choices=[('historical_novelty', 'Novedad historica'), ('main_table_observation', 'Observacion tabla principal')], max_length=32, verbose_name='origen')),
                ('status', models.CharField(choices=[('imported', 'Importada'), ('partial', 'Parcial')], default='imported', max_length=16, verbose_name='estado')),
                ('historical_section', models.CharField(blank=True, max_length=180, verbose_name='seccion historica')),
                ('historical_month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='mes historico')),
                ('historical_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ano historico')),
                ('summary', models.TextField(blank=True, verbose_name='resumen')),
                ('detail', models.TextField(blank=True, verbose_name='detalle')),
                ('source_sheet', models.CharField(max_length=150, verbose_name='hoja origen')),
                ('source_row', models.PositiveIntegerField(verbose_name='fila origen')),
                ('source_order', models.PositiveIntegerField(verbose_name='orden origen')),
                ('dedupe_key', models.CharField(max_length=64, unique=True, verbose_name='clave de deduplicacion')),
                ('source_payload', models.JSONField(blank=True, default=dict, verbose_name='payload sanitizado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualizacion')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historical_observations', to='fiduciary.fiduciaryassignment')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historical_observations', to='fiduciary.importbatch')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historical_observations', to='fiduciary.client')),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imported_historical_observations', to=settings.AUTH_USER_MODEL)),
                ('imported_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historical_observations', to='fiduciary.importedfile')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historical_observations', to='real_estate.project')),
                ('property_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historical_observations', to='real_estate.propertyunit')),
                ('related_payments', models.ManyToManyField(blank=True, related_name='historical_observations', to='fiduciary.payment')),
                ('sheet_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historical_observations', to='fiduciary.importedsheetresult')),
                ('source_novelty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='structured_observations', to='fiduciary.importedhistoricalnovelty')),
            ],
            options={
                'ordering': ('historical_year', 'historical_month', 'source_order', 'source_row', 'pk'),
                'indexes': [models.Index(fields=['origin', 'status'], name='fid_histobs_origin_status_idx'), models.Index(fields=['property_unit', 'source_order'], name='fid_histobs_unit_order_idx'), models.Index(fields=['client'], name='fid_histobs_client_idx'), models.Index(fields=['assignment'], name='fid_histobs_assignment_idx')],
            },
        ),
    ]
