# Generated by Django 5.2.16 on 2026-07-29 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0008_importedhistoricalobservation'),
        ('real_estate', '0002_remove_propertyunit_real_estate_property_unit_project_code_unique_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importedhistoricalobservation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_historical_observations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='importedhistoricalobservation',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historical_observations', to='fiduciary.importbatch'),
        ),
        migrations.AlterField(
            model_name='importedhistoricalobservation',
            name='imported_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historical_observations', to='fiduciary.importedfile'),
        ),
        migrations.AlterField(
            model_name='importedhistoricalobservation',
            name='origin',
            field=models.CharField(choices=[('historical_novelty', 'Novedad historica'), ('main_table_observation', 'Observacion tabla principal'), ('manual', 'Observacion manual')], max_length=32, verbose_name='origen'),
        ),
        migrations.AlterField(
            model_name='importedhistoricalobservation',
            name='property_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historical_observations', to='real_estate.propertyunit'),
        ),
        migrations.AlterField(
            model_name='importedhistoricalobservation',
            name='sheet_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historical_observations', to='fiduciary.importedsheetresult'),
        ),
        migrations.AlterField(
            model_name='importedhistoricalobservation',
            name='source_order',
            field=models.PositiveIntegerField(default=0, verbose_name='orden origen'),
        ),
        migrations.AlterField(
            model_name='importedhistoricalobservation',
            name='source_row',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='fila origen'),
        ),
        migrations.AlterField(
            model_name='importedhistoricalobservation',
            name='source_sheet',
            field=models.CharField(blank=True, max_length=150, verbose_name='hoja origen'),
        ),
    ]
