# Generated by Django 5.2.16 on 2026-07-29 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_historical_observations_to_novelties(apps, schema_editor):
    Observation = apps.get_model("fiduciary", "ImportedHistoricalObservation")
    OperationalNovelty = apps.get_model("fiduciary", "OperationalNovelty")
    for observation in Observation.objects.filter(origin="historical_novelty", property_unit_id__isnull=False):
        OperationalNovelty.objects.update_or_create(
            source_observation_id=observation.pk,
            defaults={
                "batch_id": observation.batch_id,
                "imported_file_id": observation.imported_file_id,
                "source_novelty_id": observation.source_novelty_id,
                "project_id": observation.project_id,
                "property_unit_id": observation.property_unit_id,
                "novelty_type": "historical",
                "origin": "historical_import",
                "status": "imported",
                "historical_client_id": observation.client_id,
                "historical_assignment_id": observation.assignment_id,
                "summary": observation.summary,
                "detail": observation.detail,
                "source_sheet": observation.source_sheet,
                "source_row": observation.source_row,
                "historical_section": observation.historical_section,
                "historical_month": observation.historical_month,
                "historical_year": observation.historical_year,
                "source_payload": observation.source_payload,
                "created_by_id": observation.imported_by_id,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0009_importedhistoricalobservation_updated_by_and_more'),
        ('real_estate', '0002_remove_propertyunit_real_estate_property_unit_project_code_unique_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalNovelty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novelty_type', models.CharField(choices=[('cession', 'Cesion'), ('withdrawal', 'Retiro'), ('exclusion', 'Exclusion'), ('substitution', 'Sustitucion'), ('administrative_correction', 'Correccion administrativa'), ('other', 'Otro'), ('historical', 'Historica importada')], max_length=32, verbose_name='tipo de novedad')),
                ('other_type', models.CharField(blank=True, max_length=120, verbose_name='cual')),
                ('origin', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatica'), ('historical_import', 'Importacion historica')], default='manual', max_length=24, verbose_name='origen')),
                ('status', models.CharField(choices=[('applied', 'Aplicada'), ('imported', 'Importada'), ('descriptive', 'Descriptiva')], default='applied', max_length=24, verbose_name='estado')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='fecha efectiva')),
                ('summary', models.TextField(blank=True, verbose_name='resumen')),
                ('detail', models.TextField(blank=True, verbose_name='detalle')),
                ('source_sheet', models.CharField(blank=True, max_length=150, verbose_name='hoja origen')),
                ('source_row', models.PositiveIntegerField(blank=True, null=True, verbose_name='fila origen')),
                ('historical_section', models.CharField(blank=True, max_length=180, verbose_name='seccion historica')),
                ('historical_month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='mes historico')),
                ('historical_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ano historico')),
                ('source_payload', models.JSONField(blank=True, default=dict, verbose_name='payload sanitizado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualizacion')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operational_novelties', to='fiduciary.importbatch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_operational_novelties', to=settings.AUTH_USER_MODEL)),
                ('historical_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historical_novelties', to='fiduciary.fiduciaryassignment')),
                ('historical_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historical_novelties', to='fiduciary.client')),
                ('imported_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operational_novelties', to='fiduciary.importedfile')),
                ('new_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='novelties_as_new_assignment', to='fiduciary.fiduciaryassignment')),
                ('new_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='novelties_as_new_client', to='fiduciary.client')),
                ('previous_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='novelties_as_previous_assignment', to='fiduciary.fiduciaryassignment')),
                ('previous_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='novelties_as_previous_client', to='fiduciary.client')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operational_novelties', to='real_estate.project')),
                ('property_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operational_novelties', to='real_estate.propertyunit')),
                ('source_novelty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operational_novelties', to='fiduciary.importedhistoricalnovelty')),
                ('source_observation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operational_novelty', to='fiduciary.importedhistoricalobservation')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['property_unit', 'created_at'], name='fid_opnov_unit_created_idx'), models.Index(fields=['novelty_type', 'origin'], name='fid_opnov_type_origin_idx'), models.Index(fields=['previous_client'], name='fid_opnov_prev_client_idx'), models.Index(fields=['new_client'], name='fid_opnov_new_client_idx'), models.Index(fields=['historical_client'], name='fid_opnov_hist_client_idx'), models.Index(fields=['previous_assignment'], name='fid_opnov_prev_assign_idx'), models.Index(fields=['new_assignment'], name='fid_opnov_new_assign_idx'), models.Index(fields=['historical_assignment'], name='fid_opnov_hist_assign_idx')],
            },
        ),
        migrations.RunPython(migrate_historical_observations_to_novelties, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='importedhistoricalobservation',
            name='origin',
            field=models.CharField(choices=[('main_table_observation', 'Observacion tabla principal'), ('manual', 'Observacion manual')], max_length=32, verbose_name='origen'),
        ),
    ]
