# Generated by Django 5.2.16 on 2026-09-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0011_importrowissue_diagnostics'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiduciaryassignment',
            name='actual_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='entrega real'),
        ),
        migrations.AddField(
            model_name='fiduciaryassignment',
            name='adhesion_contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='fecha contrato de adhesion'),
        ),
        migrations.AddField(
            model_name='fiduciaryassignment',
            name='promise_date',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de promesa'),
        ),
        migrations.AddField(
            model_name='fiduciaryassignment',
            name='promised_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='entrega segun promesa'),
        ),
    ]
