# Generated by Django 5.2.16 on 2026-09-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0013_payment_destination_dailyreportrow_payment_destination'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='fiduciary_payment_date_precision_valid',
        ),
        migrations.RemoveConstraint(
            model_name='payment',
            name='fiduciary_payment_one_date_mode',
        ),
        migrations.AddField(
            model_name='payment',
            name='historical_date_values',
            field=models.JSONField(blank=True, default=list, verbose_name='fechas historicas sin relacion determinada'),
        ),
        migrations.AddField(
            model_name='payment',
            name='historical_receipt_values',
            field=models.JSONField(blank=True, default=list, verbose_name='recibos historicos sin relacion determinada'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_precision',
            field=models.CharField(choices=[('exact', 'Fecha exacta'), ('month', 'Periodo mensual'), ('ambiguous', 'Fechas historicas ambiguas')], max_length=16, verbose_name='precision de fecha'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('date_precision__in', ['exact', 'month', 'ambiguous'])), name='fiduciary_payment_date_precision_valid'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('date_precision', 'exact'), ('exact_date__isnull', False), ('period_month__isnull', True), ('period_year__isnull', True)), models.Q(('date_precision', 'month'), ('exact_date__isnull', True), ('period_month__isnull', False), ('period_year__isnull', False)), models.Q(('date_precision', 'ambiguous'), ('exact_date__isnull', True), ('period_month__isnull', True), ('period_year__isnull', True)), _connector='OR'), name='fiduciary_payment_one_date_mode'),
        ),
    ]
