# Generated by Django 5.2.16 on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiduciary", "0014_remove_payment_fiduciary_payment_date_precision_valid_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="payment",
            name="fiduciary_payment_amount_positive",
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(condition=models.Q(("amount__gte", 0)), name="fiduciary_payment_amount_positive"),
        ),
    ]
