# Generated by Django 5.2.16 on 2026-09-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0015_allow_zero_payment_amount'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='fiduciary_payment_exact_unique',
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('date_precision', 'exact')), fields=('assignment', 'exact_date', 'amount', 'destination', 'concept'), name='fiduciary_payment_exact_unique'),
        ),
    ]
