# Generated by Django 5.2.16 on 2026-09-15 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0016_remove_payment_fiduciary_payment_exact_unique_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='importedfile',
            name='fiduciary_imported_file_historical_sha_unique',
        ),
        migrations.RemoveConstraint(
            model_name='importedfile',
            name='fiduciary_imported_file_report_sha_unique',
        ),
        migrations.AddField(
            model_name='importbatch',
            name='reverted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de reversion'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='reverted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reverted_import_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('analyzing', 'Analizando'), ('awaiting_resolution', 'Pendiente de resolucion'), ('ready', 'Listo'), ('processing', 'Procesando'), ('completed', 'Completado'), ('completed_with_issues', 'Completado con incidencias'), ('failed', 'Fallido'), ('cancelled', 'Cancelado'), ('reverted', 'Revertido')], default='pending', max_length=32, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='importedfile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('analyzing', 'Analizando'), ('ready', 'Listo'), ('processing', 'Procesando'), ('completed', 'Completado'), ('completed_with_issues', 'Completado con incidencias'), ('failed', 'Fallido'), ('duplicate', 'Duplicado'), ('cancelled', 'Cancelado'), ('reverted', 'Revertido')], default='pending', max_length=32, verbose_name='estado'),
        ),
    ]
