# Generated by Django 5.2.16 on 2026-09-16 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0017_remove_importedfile_fiduciary_imported_file_historical_sha_unique_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentLegalDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_change_reason', models.TextField(blank=True, verbose_name='ultimo motivo de modificacion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualizacion')),
                ('registration_number', models.CharField(blank=True, max_length=120, verbose_name='matricula')),
                ('deed_date', models.DateField(blank=True, null=True, verbose_name='fecha esc')),
                ('deed_number', models.CharField(blank=True, max_length=120, verbose_name='escritura')),
                ('notary', models.CharField(blank=True, max_length=120, verbose_name='notaria')),
                ('tradition_certificate_date', models.DateField(blank=True, null=True, verbose_name='fecha c/trad')),
                ('electronic_invoice', models.CharField(blank=True, max_length=120, verbose_name='factura electronica')),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='legal_documentation', to='fiduciary.fiduciaryassignment')),
            ],
            options={
                'ordering': ('assignment__assignment_number',),
            },
        ),
        migrations.CreateModel(
            name='AssignmentCreditSubsidy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_change_reason', models.TextField(blank=True, verbose_name='ultimo motivo de modificacion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualizacion')),
                ('date', models.DateField(blank=True, null=True, verbose_name='fecha')),
                ('entry_type', models.CharField(choices=[('credit', 'CRÉDITO'), ('box_subsidy', 'SUBSIDIO DE CAJA'), ('government_subsidy', 'SUBSIDIO DE GOBIERNO')], max_length=32, verbose_name='tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='valor')),
                ('entity', models.CharField(blank=True, max_length=180, verbose_name='entidad/banco')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_subsidies', to='fiduciary.fiduciaryassignment')),
            ],
            options={
                'ordering': ('date', 'pk'),
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='fiduciary_credit_subsidy_amount_positive'), models.CheckConstraint(condition=models.Q(('entry_type__in', ['credit', 'box_subsidy', 'government_subsidy'])), name='fiduciary_credit_subsidy_type_valid')],
            },
        ),
        migrations.CreateModel(
            name='AssignmentInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_change_reason', models.TextField(blank=True, verbose_name='ultimo motivo de modificacion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualizacion')),
                ('receipt', models.CharField(blank=True, max_length=120, verbose_name='recibo')),
                ('interest', models.CharField(blank=True, max_length=180, verbose_name='intereses')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='valor')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interests', to='fiduciary.fiduciaryassignment')),
            ],
            options={
                'ordering': ('pk',),
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='fiduciary_interest_amount_positive')],
            },
        ),
    ]
