# Generated by Django 5.2.16 on 2026-09-17 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0018_assignmentlegaldocumentation_assignmentcreditsubsidy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CBRImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=150, verbose_name='hoja')),
                ('row_number', models.PositiveIntegerField(verbose_name='fila origen')),
                ('original_assignment_number', models.CharField(blank=True, max_length=120, verbose_name='encargo original')),
                ('normalized_assignment_number', models.CharField(blank=True, max_length=120, verbose_name='encargo normalizado')),
                ('parsed_data', models.JSONField(blank=True, default=dict, verbose_name='datos CBR validados')),
                ('original_data', models.JSONField(blank=True, default=dict, verbose_name='datos originales sanitizados')),
                ('status', models.CharField(choices=[('valid', 'Listo'), ('blocked', 'Con incidencias'), ('imported', 'Importado'), ('skipped', 'Omitido'), ('failed', 'Fallido')], max_length=16, verbose_name='estado')),
                ('message', models.TextField(blank=True, verbose_name='mensaje')),
                ('applied_summary', models.JSONField(blank=True, default=dict, verbose_name='resumen aplicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualizacion')),
            ],
            options={
                'ordering': ('imported_file', 'sheet_name', 'row_number'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='importbatch',
            name='fiduciary_import_batch_type_valid',
        ),
        migrations.RemoveConstraint(
            model_name='importedfile',
            name='fiduciary_imported_file_type_valid',
        ),
        migrations.AlterField(
            model_name='importappliedrecord',
            name='entity_kind',
            field=models.CharField(choices=[('project', 'Proyecto'), ('grouping_type', 'Tipo de agrupacion'), ('structural_group', 'Agrupacion'), ('property_unit', 'Unidad'), ('client', 'Cliente'), ('unit_ownership', 'Titularidad'), ('fiduciary_assignment', 'Encargo fiduciario'), ('assignment_holder', 'Titular de encargo'), ('payment', 'Pago'), ('historical_novelty', 'Novedad historica'), ('daily_report_row', 'Fila de reporte diario'), ('cbr_import_row', 'Fila CBR')], max_length=32, verbose_name='tipo de entidad'),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='import_type',
            field=models.CharField(choices=[('historical', 'Historico'), ('reports', 'Reportes'), ('cbr', 'CBR')], max_length=16, verbose_name='tipo de importacion'),
        ),
        migrations.AlterField(
            model_name='importedfile',
            name='file_type',
            field=models.CharField(choices=[('historical', 'Historico'), ('report', 'Reporte'), ('cbr', 'CBR'), ('unknown', 'Desconocido')], default='unknown', max_length=16, verbose_name='tipo de archivo'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=models.Q(('import_type__in', ['historical', 'reports', 'cbr'])), name='fiduciary_import_batch_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='importedfile',
            constraint=models.CheckConstraint(condition=models.Q(('file_type__in', ['historical', 'report', 'cbr', 'unknown'])), name='fiduciary_imported_file_type_valid'),
        ),
        migrations.AddField(
            model_name='cbrimportrow',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cbr_rows', to='fiduciary.fiduciaryassignment'),
        ),
        migrations.AddField(
            model_name='cbrimportrow',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cbr_rows', to='fiduciary.importbatch'),
        ),
        migrations.AddField(
            model_name='cbrimportrow',
            name='imported_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cbr_rows', to='fiduciary.importedfile'),
        ),
        migrations.AddField(
            model_name='cbrimportrow',
            name='sheet_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cbr_rows', to='fiduciary.importedsheetresult'),
        ),
        migrations.AddIndex(
            model_name='cbrimportrow',
            index=models.Index(fields=['batch', 'status'], name='fid_cbr_row_batch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='cbrimportrow',
            index=models.Index(fields=['normalized_assignment_number'], name='fid_cbr_row_assignment_idx'),
        ),
        migrations.AddIndex(
            model_name='cbrimportrow',
            index=models.Index(fields=['assignment'], name='fid_cbr_row_assignment_fk_idx'),
        ),
        migrations.AddConstraint(
            model_name='cbrimportrow',
            constraint=models.UniqueConstraint(fields=('imported_file', 'sheet_name', 'row_number'), name='fid_cbr_row_file_sheet_row_unique'),
        ),
        migrations.AddConstraint(
            model_name='cbrimportrow',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['valid', 'blocked', 'imported', 'skipped', 'failed'])), name='fid_cbr_row_status_valid'),
        ),
    ]
