# Generated by Django 5.2.16 on 2026-09-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0019_cbrimportrow_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assignmentcreditsubsidy',
            constraint=models.UniqueConstraint(fields=('assignment', 'entry_type'), name='fiduciary_credit_subsidy_assignment_type_unique'),
        ),
    ]
