from django.urls import path

from .views import (
    AssignmentCloseView,
    AssignmentChangeView,
    AssignmentContextGroupsView,
    AssignmentContextHoldersView,
    AssignmentContextTypesView,
    AssignmentContextUnitsView,
    AssignmentCreateView,
    AssignmentDeleteView,
    AssignmentDetailView,
    AssignmentFinancialEntityUpdateView,
    AssignmentHolderCreateView,
    AssignmentHolderFinalizeView,
    AssignmentListView,
    AssignmentPaymentCreateView,
    AssignmentSecondaryCreateView,
    AssignmentUpdateView,
    AuditDetailView,
    AuditListView,
    ClientCreateView,
    ClientDeleteView,
    ClientDetailView,
    ClientListView,
    ClientSearchView,
    ClientStatusView,
    ClientUpdateView,
    DailyReportBatchListView,
    DailyReportCancelView,
    DailyReportCreateView,
    DailyReportFinalizeView,
    DailyReportPreviewView,
    DailyReportReanalyzeView,
    DailyReportRevertView,
    DailyReportResolveAssignmentView,
    ExportHomeView,
    HistoricalImportBatchListView,
    HistoricalImportCancelView,
    HistoricalImportCreateView,
    HistoricalImportFinalizeView,
    HistoricalImportIssueDetailView,
    HistoricalImportPendingListView,
    HistoricalImportProgressPageView,
    HistoricalImportProgressView,
    HistoricalImportPreviewView,
    HistoricalImportReanalyzePendingView,
    HistoricalImportRevertView,
    HistoricalImportResolutionView,
    HistoricalImportStructuralGroupChoicesView,
    HistoricalImportStructuralGroupResolutionView,
    ImportUploadSummaryView,
    NoveltyCreateView,
    NoveltyAssignmentClientsView,
    NoveltyClientSearchView,
    NoveltyDeleteView,
    NoveltyDetailView,
    NoveltyUpdateView,
    NoveltyListView,
    ObservationContextView,
    ObservationCreateView,
    ObservationDeleteView,
    ObservationDetailView,
    ObservationListView,
    ObservationUpdateView,
    PaymentListView,
    PaymentCreateView,
    PaymentDeleteView,
    PaymentUpdateView,
    PaymentUnitAssignmentView,
    HistoricalWorkbookExportView,
    UnitHierarchyGroupsView,
    UnitHierarchyTypesView,
    UnitHierarchyUnitsView,
    UnitOwnershipCreateView,
    UnitOwnershipFinalizeView,
    UnitOwnershipListView,
    UploadedDocumentDownloadView,
    PrimaryOwnershipChangeView,
)


app_name = "fiduciary"

urlpatterns = [
    path("imports/upload-summary/", ImportUploadSummaryView.as_view(), name="import_upload_summary"),
    path("historical-imports/", HistoricalImportBatchListView.as_view(), name="historical_import_list"),
    path("historical-imports/new/", HistoricalImportCreateView.as_view(), name="historical_import_create"),
    path("historical-imports/<int:pk>/", HistoricalImportPreviewView.as_view(), name="historical_import_preview"),
    path("historical-imports/<int:pk>/processing/", HistoricalImportProgressPageView.as_view(), name="historical_import_progress_page"),
    path("historical-imports/<int:pk>/progress/", HistoricalImportProgressView.as_view(), name="historical_import_progress"),
    path("historical-imports/<int:pk>/issues/", HistoricalImportIssueDetailView.as_view(), name="historical_import_issues"),
    path("historical-imports/<int:pk>/finalize/", HistoricalImportFinalizeView.as_view(), name="historical_import_finalize"),
    path("historical-imports/<int:pk>/cancel/", HistoricalImportCancelView.as_view(), name="historical_import_cancel"),
    path("historical-imports/<int:pk>/revert/", HistoricalImportRevertView.as_view(), name="historical_import_revert"),
    path("historical-imports/<int:pk>/pending/", HistoricalImportPendingListView.as_view(), name="historical_import_pending"),
    path(
        "historical-imports/<int:pk>/pending/reanalyze/",
        HistoricalImportReanalyzePendingView.as_view(),
        name="historical_import_reanalyze_pending",
    ),
    path(
        "historical-imports/<int:pk>/pending/<int:element_pk>/resolve/",
        HistoricalImportResolutionView.as_view(),
        name="historical_import_resolve",
    ),
    path(
        "historical-imports/<int:pk>/pending/<int:element_pk>/resolve-group/",
        HistoricalImportStructuralGroupResolutionView.as_view(),
        name="historical_import_resolve_group",
    ),
    path(
        "historical-imports/context/groups/",
        HistoricalImportStructuralGroupChoicesView.as_view(),
        name="historical_import_context_groups",
    ),
    path("daily-reports/", DailyReportBatchListView.as_view(), name="daily_report_list"),
    path("daily-reports/new/", DailyReportCreateView.as_view(), name="daily_report_create"),
    path("daily-reports/<int:pk>/", DailyReportPreviewView.as_view(), name="daily_report_preview"),
    path("daily-reports/<int:pk>/reanalyze/", DailyReportReanalyzeView.as_view(), name="daily_report_reanalyze"),
    path("daily-reports/<int:pk>/cancel/", DailyReportCancelView.as_view(), name="daily_report_cancel"),
    path("daily-reports/<int:pk>/revert/", DailyReportRevertView.as_view(), name="daily_report_revert"),
    path("daily-reports/<int:pk>/finalize/", DailyReportFinalizeView.as_view(), name="daily_report_finalize"),
    path("daily-reports/<int:pk>/rows/<int:row_pk>/resolve/", DailyReportResolveAssignmentView.as_view(), name="daily_report_resolve"),
    path("clients/", ClientListView.as_view(), name="client_list"),
    path("clients/new/", ClientCreateView.as_view(), name="client_create"),
    path("clients/<int:pk>/", ClientDetailView.as_view(), name="client_detail"),
    path("clients/<int:pk>/edit/", ClientUpdateView.as_view(), name="client_update"),
    path("clients/<int:pk>/delete/", ClientDeleteView.as_view(), name="client_delete"),
    path("clients/<int:pk>/<str:action>/", ClientStatusView.as_view(), name="client_status"),
    path("clients/search/", ClientSearchView.as_view(), name="client_search"),
    path("observations/", ObservationListView.as_view(), name="observation_list"),
    path("observations/new/", ObservationCreateView.as_view(), name="observation_create"),
    path("observations/context/", ObservationContextView.as_view(), name="observation_context"),
    path("units/context/types/", UnitHierarchyTypesView.as_view(), name="unit_context_types"),
    path("units/context/groups/", UnitHierarchyGroupsView.as_view(), name="unit_context_groups"),
    path("units/context/units/", UnitHierarchyUnitsView.as_view(), name="unit_context_units"),
    path("observations/<int:pk>/", ObservationDetailView.as_view(), name="observation_detail"),
    path("observations/<int:pk>/edit/", ObservationUpdateView.as_view(), name="observation_update"),
    path("observations/<int:pk>/delete/", ObservationDeleteView.as_view(), name="observation_delete"),
    path("novelties/", NoveltyListView.as_view(), name="novelty_list"),
    path("novelties/new/", NoveltyCreateView.as_view(), name="novelty_create"),
    path("novelties/context/assignment-clients/", NoveltyAssignmentClientsView.as_view(), name="novelty_assignment_clients"),
    path("novelties/context/client-search/", NoveltyClientSearchView.as_view(), name="novelty_client_search"),
    path("novelties/<int:pk>/", NoveltyDetailView.as_view(), name="novelty_detail"),
    path("novelties/<int:pk>/edit/", NoveltyUpdateView.as_view(), name="novelty_update"),
    path("novelties/<int:pk>/delete/", NoveltyDeleteView.as_view(), name="novelty_delete"),
    path("payments/", PaymentListView.as_view(), name="payment_list"),
    path("payments/new/", PaymentCreateView.as_view(), name="payment_create"),
    path("payments/<int:pk>/edit/", PaymentUpdateView.as_view(), name="payment_update"),
    path("payments/<int:pk>/delete/", PaymentDeleteView.as_view(), name="payment_delete"),
    path("payments/context/unit-assignment/", PaymentUnitAssignmentView.as_view(), name="payment_unit_assignment"),
    path("exports/", ExportHomeView.as_view(), name="export_home"),
    path("exports/historical-workbook/", HistoricalWorkbookExportView.as_view(), name="export_historical_workbook"),
    path("exports/documents/<int:pk>/download/", UploadedDocumentDownloadView.as_view(), name="export_document_download"),
    path("audit/", AuditListView.as_view(), name="audit_list"),
    path("audit/<int:pk>/", AuditDetailView.as_view(), name="audit_detail"),
    path("ownerships/", UnitOwnershipListView.as_view(), name="ownership_list"),
    path("ownerships/new/", UnitOwnershipCreateView.as_view(), name="ownership_create"),
    path("ownerships/<int:pk>/finalize/", UnitOwnershipFinalizeView.as_view(), name="ownership_finalize"),
    path("ownerships/<int:pk>/change-primary/", PrimaryOwnershipChangeView.as_view(), name="ownership_change_primary"),
    path("assignments/", AssignmentListView.as_view(), name="assignment_list"),
    path("assignments/new/", AssignmentCreateView.as_view(), name="assignment_create"),
    path("assignments/context/types/", AssignmentContextTypesView.as_view(), name="assignment_context_types"),
    path("assignments/context/groups/", AssignmentContextGroupsView.as_view(), name="assignment_context_groups"),
    path("assignments/context/units/", AssignmentContextUnitsView.as_view(), name="assignment_context_units"),
    path("assignments/context/holders/", AssignmentContextHoldersView.as_view(), name="assignment_context_holders"),
    path("assignments/<int:pk>/", AssignmentDetailView.as_view(), name="assignment_detail"),
    path("assignments/<int:pk>/delete/", AssignmentDeleteView.as_view(), name="assignment_delete"),
    path("assignments/<int:pk>/financial-entity/", AssignmentFinancialEntityUpdateView.as_view(), name="assignment_financial_entity_update"),
    path("assignments/<int:pk>/payments/new/", AssignmentPaymentCreateView.as_view(), name="assignment_payment_create"),
    path("assignments/<int:pk>/edit/", AssignmentUpdateView.as_view(), name="assignment_update"),
    path("assignments/<int:pk>/close/", AssignmentCloseView.as_view(), name="assignment_close"),
    path("assignments/<int:pk>/change/", AssignmentChangeView.as_view(), name="assignment_change"),
    path("assignments/<int:assignment_pk>/secondaries/new/", AssignmentSecondaryCreateView.as_view(), name="assignment_secondary_create"),
    path("assignments/<int:assignment_pk>/holders/new/", AssignmentHolderCreateView.as_view(), name="holder_create"),
    path("assignment-holders/<int:pk>/finalize/", AssignmentHolderFinalizeView.as_view(), name="holder_finalize"),
]
