from django.urls import path

from .views import (
    AssignmentCloseView,
    AssignmentChangeView,
    AssignmentContextGroupsView,
    AssignmentContextHoldersView,
    AssignmentContextTypesView,
    AssignmentContextUnitsView,
    AssignmentCreateView,
    AssignmentDetailView,
    AssignmentHolderCreateView,
    AssignmentHolderFinalizeView,
    AssignmentListView,
    AssignmentUpdateView,
    AuditDetailView,
    AuditListView,
    ClientCreateView,
    ClientDetailView,
    ClientListView,
    ClientSearchView,
    ClientStatusView,
    ClientUpdateView,
    DailyReportBatchListView,
    DailyReportCancelView,
    DailyReportCreateView,
    DailyReportFinalizeView,
    DailyReportPreviewView,
    DailyReportReanalyzeView,
    DailyReportResolveAssignmentView,
    HistoricalImportBatchListView,
    HistoricalImportCancelView,
    HistoricalImportCreateView,
    HistoricalImportFinalizeView,
    HistoricalImportPendingListView,
    HistoricalImportPreviewView,
    HistoricalImportReanalyzePendingView,
    HistoricalImportResolutionView,
    HistoricalImportStructuralGroupChoicesView,
    HistoricalImportStructuralGroupResolutionView,
    ImportUploadSummaryView,
    NoveltyCreateView,
    NoveltyDetailView,
    NoveltyListView,
    ObservationContextView,
    ObservationCreateView,
    ObservationDetailView,
    ObservationListView,
    ObservationUpdateView,
    PaymentListView,
    UnitOwnershipCreateView,
    UnitOwnershipFinalizeView,
    UnitOwnershipListView,
    PrimaryOwnershipChangeView,
)


app_name = "fiduciary"

urlpatterns = [
    path("imports/upload-summary/", ImportUploadSummaryView.as_view(), name="import_upload_summary"),
    path("historical-imports/", HistoricalImportBatchListView.as_view(), name="historical_import_list"),
    path("historical-imports/new/", HistoricalImportCreateView.as_view(), name="historical_import_create"),
    path("historical-imports/<int:pk>/", HistoricalImportPreviewView.as_view(), name="historical_import_preview"),
    path("historical-imports/<int:pk>/finalize/", HistoricalImportFinalizeView.as_view(), name="historical_import_finalize"),
    path("historical-imports/<int:pk>/cancel/", HistoricalImportCancelView.as_view(), name="historical_import_cancel"),
    path("historical-imports/<int:pk>/pending/", HistoricalImportPendingListView.as_view(), name="historical_import_pending"),
    path(
        "historical-imports/<int:pk>/pending/reanalyze/",
        HistoricalImportReanalyzePendingView.as_view(),
        name="historical_import_reanalyze_pending",
    ),
    path(
        "historical-imports/<int:pk>/pending/<int:element_pk>/resolve/",
        HistoricalImportResolutionView.as_view(),
        name="historical_import_resolve",
    ),
    path(
        "historical-imports/<int:pk>/pending/<int:element_pk>/resolve-group/",
        HistoricalImportStructuralGroupResolutionView.as_view(),
        name="historical_import_resolve_group",
    ),
    path(
        "historical-imports/context/groups/",
        HistoricalImportStructuralGroupChoicesView.as_view(),
        name="historical_import_context_groups",
    ),
    path("daily-reports/", DailyReportBatchListView.as_view(), name="daily_report_list"),
    path("daily-reports/new/", DailyReportCreateView.as_view(), name="daily_report_create"),
    path("daily-reports/<int:pk>/", DailyReportPreviewView.as_view(), name="daily_report_preview"),
    path("daily-reports/<int:pk>/reanalyze/", DailyReportReanalyzeView.as_view(), name="daily_report_reanalyze"),
    path("daily-reports/<int:pk>/cancel/", DailyReportCancelView.as_view(), name="daily_report_cancel"),
    path("daily-reports/<int:pk>/finalize/", DailyReportFinalizeView.as_view(), name="daily_report_finalize"),
    path("daily-reports/<int:pk>/rows/<int:row_pk>/resolve/", DailyReportResolveAssignmentView.as_view(), name="daily_report_resolve"),
    path("clients/", ClientListView.as_view(), name="client_list"),
    path("clients/new/", ClientCreateView.as_view(), name="client_create"),
    path("clients/<int:pk>/", ClientDetailView.as_view(), name="client_detail"),
    path("clients/<int:pk>/edit/", ClientUpdateView.as_view(), name="client_update"),
    path("clients/<int:pk>/<str:action>/", ClientStatusView.as_view(), name="client_status"),
    path("clients/search/", ClientSearchView.as_view(), name="client_search"),
    path("observations/", ObservationListView.as_view(), name="observation_list"),
    path("observations/new/", ObservationCreateView.as_view(), name="observation_create"),
    path("observations/context/", ObservationContextView.as_view(), name="observation_context"),
    path("observations/<int:pk>/", ObservationDetailView.as_view(), name="observation_detail"),
    path("observations/<int:pk>/edit/", ObservationUpdateView.as_view(), name="observation_update"),
    path("novelties/", NoveltyListView.as_view(), name="novelty_list"),
    path("novelties/new/", NoveltyCreateView.as_view(), name="novelty_create"),
    path("novelties/<int:pk>/", NoveltyDetailView.as_view(), name="novelty_detail"),
    path("payments/", PaymentListView.as_view(), name="payment_list"),
    path("audit/", AuditListView.as_view(), name="audit_list"),
    path("audit/<int:pk>/", AuditDetailView.as_view(), name="audit_detail"),
    path("ownerships/", UnitOwnershipListView.as_view(), name="ownership_list"),
    path("ownerships/new/", UnitOwnershipCreateView.as_view(), name="ownership_create"),
    path("ownerships/<int:pk>/finalize/", UnitOwnershipFinalizeView.as_view(), name="ownership_finalize"),
    path("ownerships/<int:pk>/change-primary/", PrimaryOwnershipChangeView.as_view(), name="ownership_change_primary"),
    path("assignments/", AssignmentListView.as_view(), name="assignment_list"),
    path("assignments/new/", AssignmentCreateView.as_view(), name="assignment_create"),
    path("assignments/context/types/", AssignmentContextTypesView.as_view(), name="assignment_context_types"),
    path("assignments/context/groups/", AssignmentContextGroupsView.as_view(), name="assignment_context_groups"),
    path("assignments/context/units/", AssignmentContextUnitsView.as_view(), name="assignment_context_units"),
    path("assignments/context/holders/", AssignmentContextHoldersView.as_view(), name="assignment_context_holders"),
    path("assignments/<int:pk>/", AssignmentDetailView.as_view(), name="assignment_detail"),
    path("assignments/<int:pk>/edit/", AssignmentUpdateView.as_view(), name="assignment_update"),
    path("assignments/<int:pk>/close/", AssignmentCloseView.as_view(), name="assignment_close"),
    path("assignments/<int:pk>/change/", AssignmentChangeView.as_view(), name="assignment_change"),
    path("assignments/<int:assignment_pk>/holders/new/", AssignmentHolderCreateView.as_view(), name="holder_create"),
    path("assignment-holders/<int:pk>/finalize/", AssignmentHolderFinalizeView.as_view(), name="holder_finalize"),
]
